version: '3'
services:
  server-mlbio-project:
    build: .
    container_name: server-mlbio-project
    ports:
      - "127.0.0.1:8089:8089"
    environment:
      - MODEL=resnet34
    command: python src/server.py 
